feat: add APIs of board microservice
spaceone-dev/api pull request #280
Opened 2022-04-07 08:02 UTC by stat-kwon

2022-04-07 08:50 UTC, jihyungSong approved these changes
LGTM.
confirmation plz for cross-check.

2022-04-07 09:11 UTC, whdalsrnt requested changes
Change description

2022-04-07 09:11 UTC, whdalsrnt commented on proto/spaceone/api/board/v1/post.proto
> +  // is_required: true
Change optional value

2022-04-07 09:11 UTC, whdalsrnt commented on proto/spaceone/api/board/v1/post.proto
> +  // is_required: true
Change optional value

2022-04-07 09:11 UTC, whdalsrnt commented on proto/spaceone/api/board/v1/post.proto
> +  // is_required: true
Change optional value

2022-04-07 09:11 UTC, whdalsrnt commented on proto/spaceone/api/board/v1/post.proto
> +  // is_required: true
Change optional value

2022-04-08 01:32 UTC, stat-kwon commented on proto/spaceone/api/board/v1/post.proto
> +  // is_required: true
I have edited the part you mentioned.

2022-04-08 01:32 UTC, stat-kwon commented
I have edited the part you mentioned.

2022-04-15 09:20 UTC, whdalsrnt requested changes

2022-04-15 09:20 UTC, whdalsrnt commented on proto/spaceone/api/board/v1/post.proto
> +  string user_id = 11;
Remove user_id field.
The user_id field comes from metadata, not from passing parameters.

2022-04-18 01:47 UTC, whdalsrnt approved these changes

2022-04-18 02:04 UTC, merged